import {
    PiPuzzlePieceDuotone,
    PiSwatchesDuotone,
    PiChatDotsDuotone,
    PiDesktopDuotone,
    PiFileTextDuotone,
    PiCompassDuotone,
    PiChartPieSliceDuotone,
    PiUsersDuotone,
    PiPackageDuotone,
    PiProjectorScreenChartDuotone,
    PiShoppingCartDuotone,
    PiCalendarDuotone,
    PiFolderOpenDuotone,
    PiEnvelopeDuotone,
    PiUserCircleDuotone,
    PiSparkleDuotone,
    PiChatCircleDuotone,
    PiQuestionDuotone,
    PiShieldCheckDuotone,
    PiUserPlusDuotone,
    PiLockKeyOpenDuotone,
    PiKeyDuotone,
    // PiShoppingCartSimpleDuotone,
    // PiRocketDuotone,
    // PiChartBarDuotone,
    // PiMegaphoneDuotone,
    // PiSpeedometerDuotone,
    PiLightbulbDuotone,
    PiKeyholeDuotone,
    PiChatCenteredDotsDuotone,
    PiImagesDuotone,
    PiChalkboardSimpleDuotone,
    PiListChecksDuotone,
    PiUserListDuotone,
    PiListStarDuotone,
    PiFileMagnifyingGlassDuotone,
    PiCalendarCheckDuotone,
    PiWarningDuotone,
    PiPencilSimpleLineDuotone,
    PiNotePencilDuotone,
    PiPlusSquareDuotone,
    PiListPlusDuotone,
    PiFilmScriptDuotone,
    PiStackPlusDuotone,
    PiListMagnifyingGlassDuotone,
    PiGearDuotone,
    PiUserGearDuotone,
    PiCurrencyCircleDollarDuotone,
    PiNewspaperDuotone,
    PiHeadsetDuotone,
    PiQuotesDuotone,
    PiTextIndentDuotone,
    PiCursorClickDuotone,
    PiGridFourDuotone,
    PiTextAaDuotone,
    PiHandWithdrawDuotone,
    PiSpinnerGapDuotone,
    PiBoneDuotone,
    PiSpinnerBallDuotone,
    PiBreadDuotone,
    PiMedalDuotone,
    PiCardsDuotone,
    PiTableDuotone,
    PiTagDuotone,
    PiClockCountdownDuotone,
    PiChatCenteredDuotone,
    PiCheckSquareDuotone,
    PiClipboardTextDuotone,
    PiRowsDuotone,
    PiRowsPlusBottomDuotone,
    PiRadioButtonDuotone,
    PiChartDonutDuotone,
    PiListChecksBold,
    PiToggleRightDuotone,
    PiClockAfternoonDuotone,
    PiUploadDuotone,
    PiCaretCircleDownDuotone,
    PiListDuotone,
    PiCodeSimpleDuotone,
    PiFootprintsDuotone,
    PiBrowsersDuotone,
    PiChartLineUpDuotone,
    PiMapTrifoldDuotone,
    PiBookDuotone,
    PiShareNetworkDuotone,
    PiToolboxDuotone,
    PiCodeDuotone,
    PiPasswordDuotone,
    PiDotsThreeCircleDuotone,
    PiCircleHalfTiltDuotone,
    PiHouseLineDuotone,
} from 'react-icons/pi'

import { MdOutlineHome } from "react-icons/md";
import { FaSearchPlus } from "react-icons/fa";
import { MdMyLocation } from "react-icons/md";
import { IoCartOutline } from "react-icons/io5";
import { IoMdSettings } from "react-icons/io";
import { AiTwotoneExperiment } from "react-icons/ai";
import { GoGraph } from "react-icons/go";
import { LuSquareTerminal } from "react-icons/lu";
import { PiBagSimple } from "react-icons/pi";

const navigationIcon = {
    uiComponents: <PiPuzzlePieceDuotone />,
    common: <PiSwatchesDuotone />,
    uiCommonButton: <PiCursorClickDuotone />,
    uiCommonGrid: <PiGridFourDuotone />,
    uiCommonTypography: <PiTextAaDuotone />,
    uiCommonIcons: <PiImagesDuotone />,
    feedback: <PiChatDotsDuotone />,
    uiFeedbackAlert: <PiWarningDuotone />,
    uiFeedbackDialog: <PiChatCircleDuotone />,
    uiFeedbackDrawer: <PiHandWithdrawDuotone />,
    uiFeedbackProgress: <PiSpinnerGapDuotone />,
    uiFeedbackSkeleton: <PiBoneDuotone />,
    uiFeedbackSpinner: <PiSpinnerBallDuotone />,
    uiFeedbackToast: <PiBreadDuotone />,
    dataDisplay: <PiDesktopDuotone />,
    uiDataDisplayAvatar: <PiUserCircleDuotone />,
    uiDataDisplayBadge: <PiMedalDuotone />,
    uiDataDisplayCalendar: <PiCalendarDuotone />,
    uiDataDisplayCard: <PiCardsDuotone />,
    uiDataDisplayTable: <PiTableDuotone />,
    uiDataDisplayTag: <PiTagDuotone />,
    uiDataDisplayTimeline: <PiClockCountdownDuotone />,
    uiDataDisplayTooltip: <PiChatCenteredDuotone />,
    forms: <PiFileTextDuotone />,
    uiFormsCheckbox: <PiCheckSquareDuotone />,
    uiFormsDatepicker: <PiCalendarCheckDuotone />,
    uiFormsFormControl: <PiClipboardTextDuotone />,
    uiFormsInput: <PiRowsDuotone />,
    uiFormsInputGroup: <PiRowsPlusBottomDuotone />,
    uiFormsRadio: <PiRadioButtonDuotone />,
    uiFormsSegment: <PiChartDonutDuotone />,
    uiFormsSelect: <PiListChecksBold />,
    uiFormsSwitcher: <PiToggleRightDuotone />,
    uiFormsTimePicker: <PiClockAfternoonDuotone />,
    uiFormsUpload: <PiUploadDuotone />,
    navigation: <PiCompassDuotone />,
    uiNavigationDropdown: <PiCaretCircleDownDuotone />,
    uiNavigationMenu: <PiListDuotone />,
    uiNavigationPagination: <PiCodeSimpleDuotone />,
    uiNavigationSteps: <PiFootprintsDuotone />,
    uiNavigationTabs: <PiBrowsersDuotone />,
    graph: <PiChartPieSliceDuotone />,
    uiGraphChart: <PiChartLineUpDuotone />,
    uiGraphMaps: <PiMapTrifoldDuotone />,
    concepts: <PiLightbulbDuotone />,
    customers: <LuSquareTerminal />,
    customerList: <PiUserListDuotone />,
    customerEdit: <PiPencilSimpleLineDuotone />,
    customerCreate: <PiUserPlusDuotone />,
    customerDetails: <PiUserCircleDuotone />,
    products: <AiTwotoneExperiment />,
    productList: <PiListStarDuotone />,
    productEdit: <PiNotePencilDuotone />,
    productCreate: <PiPlusSquareDuotone />,
    projects: <IoCartOutline />,
    projectScrumBoard: <PiChalkboardSimpleDuotone />,
    projectList: <PiListChecksDuotone />,
    projectDetails: <PiFileMagnifyingGlassDuotone />,
    projectTask: <PiCalendarCheckDuotone />,
    projectIssue: <PiWarningDuotone />,
    orders: <AiTwotoneExperiment />,
    orderList: <PiListPlusDuotone />,
    orderEdit: <PiFilmScriptDuotone />,
    ordeDetails: <PiListMagnifyingGlassDuotone />,
    orderCreate: <PiStackPlusDuotone />,
    calendar: <PiCalendarDuotone />,
    fileManager: <PiFolderOpenDuotone />,
    mail: <PiEnvelopeDuotone />,
    account: <PiUserCircleDuotone />,
    accountSettings: <PiGearDuotone />,
    accountActivityLogs: <PiFileTextDuotone />,
    accountRoleAndPermission: <PiUserGearDuotone />,
    accountPricing: <PiCurrencyCircleDollarDuotone />,
    ai: <MdMyLocation />,
    aiChat: <PiChatCenteredDotsDuotone />,
    aiImage: <PiImagesDuotone />,
    chat: <PiChatCircleDuotone />,
    helpCenter: <IoMdSettings />,
    helpCeterSupportHub: <PiHeadsetDuotone />,
    helpCeterArticle: <PiNewspaperDuotone />,
    helpCeterEditArticle: <PiTextIndentDuotone />,
    helpCeterManageArticle: <PiQuotesDuotone />,
    authentication: <PiShieldCheckDuotone />,
    signIn: <PiKeyDuotone />,
    signUp: <PiUserPlusDuotone />,
    forgotPassword: <PiLockKeyOpenDuotone />,
    resetPassword: <PiKeyholeDuotone />,
    otpVerification: <PiPasswordDuotone />,
    // dashboard: <PiSpeedometerDuotone />,
    dashboardEcommerce: <MdOutlineHome />,
    dashboardProject: <PiBagSimple />,
    // dashboardAnalytic: <PiChartBarDuotone />,
    // dashboardMarketing: <FaSearchPlus />,
    others: <PiDotsThreeCircleDuotone />,
    accessDenied: <PiCircleHalfTiltDuotone />,
    landing: <PiHouseLineDuotone />,
    documentation: <PiBookDuotone />,
    sharedComponentDoc: <PiShareNetworkDuotone />,
    utilsDoc: <PiToolboxDuotone />,
    changeLog: <PiCodeDuotone />,
}

export default navigationIcon
